#%RAML 1.0 NamedExample
value:
  {
    "first_name": "Jane",
    "last_name": "Thompson",
    "address": {
      "address_line_1": "1234 Boulevard",
      "city": "Los Angeles",
      "zip_code": "90210",
      "state": "California",
      "country": "USA"
    },
    "phone": "52155654",
  }